from enum import Enum

class Status(Enum):
	ongoing		= 'Ongoing'
	completed	= 'Completed'

class Genre(Enum):
	action			= 'Action'
	adult			= 'Adult'
	adventure		= 'Adventure'
	comedy			= 'Comedy'
	demons			= 'Demons'
	drama			= 'Drama'
	ecchi			= 'Ecchi'
	fantasy			= 'Fantasy'
	gender_bender	= 'Gender Bender'
	harem			= 'Harem'
	historical		= 'Historical'
	horror			= 'Horror'
	josei			= 'Josei'
	magic			= 'Magic'
	martial_arts	= 'Martial Arts'
	mature			= 'Mature'
	mecha			= 'Mecha'
	military		= 'Military'
	mystery			= 'Mystery'
	one_shot		= 'One Shot'
	psychological	= 'Psychological'
	romance			= 'Romance'
	school_life		= 'School Life'
	sci_fi			= 'Sci-Fi'
	seinen			= 'Seinen'
	shoujo			= 'Shoujo'
	shoujo_ai 		= 'Shoujoai'
	shounen			= 'Shounen'
	shounen_ai 		= 'Shounenai'
	slice_of_life	= 'Slice of Life'
	smut			= 'Smut'
	sports			= 'Sports'
	superpower		= 'Super Power'
	supernatural	= 'Supernatural'
	tragedy			= 'Tragedy'
	vampire			= 'Vampire'
	yaoi			= 'Yaoi'
	yuri			= 'Yuri'

class ReadingDirection(Enum):
	left_to_right = 'Left to Right'
	right_to_left = 'Right to Left'